### ISSUE TITLE
Fix lab statements

### ISSUE THREAD

**Issue by divijan** [akraievoy/elw#31]
1. lab3-5: 8 students wrote the same code. I'm sort of worried.
2. Should we specify what actions need to be moved into sub-procedure in lab6?

**Comment by akraievoy** [comment]
Снижай за групповуху. Второму один раз - остальным по два. Других вариантов
я особо не вижу.
Авторизацию я впилить не успею уже скорее всего. Разве что по имейлу.

2011/12/19 divijan <
reply@reply.github.com

> 8 students wrote the same code. I'm sort of worried.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/akraievoy/elw/issues/31

## 

[ http://akraievoy.org ]

**Comment by divijan** [comment]
Авторизация мне даже в голову не приходила. Мне кажется, что дело в задании. Оно, наверное, слишком естественно укладывается в код, просто no-brainer:
`Зменшити вміст регістра $a0 на значення
регістру $a1, в випадку, якщо результат менше значення регістру $a1, записати
в $v0 1, інакше записати 0.`

**Comment by divijan** [comment]
Statement for 6-6 was reformulated to specify sources of input data. 6-5 statement changed slightly.
3-4 changed to "Збільшити вміст регістра $a0 на 2; у випадку, якщо результат більше 0, збільшити вміст $v0 на 1." and tests changed accordingly.
3-5 changed to "Зменшити вміст регістра $a0 на значення регістру $a1; у випадку, якщо результат менше значення регістру $a1, записати його (результат) в $v0.", tests changed accordingly.
