### ISSUE TITLE
The code passes tests, but is shown as Pending

### ISSUE THREAD

**Issue by divijan** [akraievoy/elw#33]
That is, it passes tests when tested from student's account, but in the table it appears Pending to both admin and the student.

**Comment by divijan** [comment]
This happened to Оксана Базалій & Євген Каліта. In both cases it was code for lab 4.

**Comment by akraievoy** [comment]
Apparent dupe of #46

**Comment by divijan** [comment]
Nope. If it was, #46 would be fixed too.
