### ISSUE TITLE
Can't submit code: PUT failed

### ISSUE THREAD

**Issue by divijan** [akraievoy/elw#40]
I get a "Failed: PUT failed." message in status bar when I try to submit code for first or second lab (didn't try other labs). Also, when I try to upload a report, I get this page:
<html><body><h3>HTTP status 500 : PUT failed</h3>Sorry for inconvenience and thanks for finding just another bug out there.<br/>For the time being, you may log out, log in and then try the operation once again.<br/><br/>Event reference id: <b>gz2b1xa7</b>.</body></html>

**Comment by divijan** [comment]
My guess is you forgot to grant users permissions to use PUT request on the web server. Let me know if I'm right. BTW, is using standard HTTP requests as an API for your web application all there is to your REST interface?

**Comment by akraievoy** [comment]
No. elw-mvc-servlet.xml was deployed with incorrect auth for local couch. So reads passed while writes did not. That was the only problem. Obviously I need to spend some time on proper config injection to avoid this problem in future.

ReST: not so simple, I found myself rewriting most of the code in quite cleaner way than before. Security/data filtering is now way more modular. Actually ReST is not completely standard HTTP as PUT uploads are not supported by browsers for example. See comments in ControllerRest for more examples.
