### ISSUE TITLE
Code state cannot be changed to approved/declined by hand

### ISSUE THREAD

**Issue by divijan** [akraievoy/elw#46]
I decided I'd create an issue for this just to be consistent.
The history of slot states shows all approvals, but the latest state is invariably pending. The codes also show up when Pending@Student is selected in the filter. 
This happened to students number 13 and 18 from KA-91 (don't want to divulge their names here) and their lab 3, version 3. One of the tests was screwed up, so I promised them I will fix it and approve their codes manually.

**Comment by akraievoy** [comment]
fixed in rev. 1c4d329a5b7825f5da4fbb4df448facc8b510a09
